/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ActorType = "client_user" | "consumer" | "integration" | "staff_user" | "system";

export type AssignedBy = "router" | "staff";

export type AssignmentStatus = "accepted" | "cancelled" | "delivery_failed" | "disputed" | "expired" | "notified" | "refunded" | "rejected" | "reserved";

export type BillingMode = "invoice" | "prepaid";

export type ChangeRequestKind = "coverage" | "other" | "services";

export type ChangeRequestStatus = "done" | "open";

export type ChargeSource = "credit_balance" | "included_allowance" | "invoice";

export type ChargeStatus = "posted" | "reversed";

export type ClientStatus = "active" | "churned" | "paused" | "prospect" | "suspended";

export type ClientUserRole = "agent" | "manager" | "owner";

export type ClientUserStatus = "active" | "disabled" | "invited";

export type ConsentEventType = "granted" | "withdrawn";

export type ContactOutcome = "left_voicemail" | "lost" | "no_answer" | "not_interested" | "quote_sent" | "spoke" | "won" | "wrong_number";

export type CoverageKind = "area" | "outward" | "postcode_prefix" | "radius" | "sector";

export type CoverageMode = "exclude" | "include";

export type DeliveryMode = "automatic" | "manual";

export type DisputeReason = "duplicate" | "not_as_described" | "not_homeowner" | "other" | "out_of_area" | "spam" | "wrong_number";

export type DisputeResolution = "credit_refund" | "replacement_lead";

export type DisputeStatus = "open" | "rejected" | "under_review" | "upheld" | "withdrawn";

export type FraudDecision = "accept" | "flag" | "reject" | "review";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type LeadSourceKind = "direct" | "organic" | "paid_search" | "paid_social" | "partner" | "referral" | "unknown";

export type LeadStatus = "assigned" | "duplicate" | "expired" | "held" | "invalid" | "new" | "rejected_fraud" | "routing" | "unroutable";

export type LedgerEntryType = "adjustment" | "expiry" | "grant" | "lead_charge" | "refund" | "top_up";

export type NotificationChannel = "email" | "sms" | "webhook";

export type NotificationStatus = "cancelled" | "dead" | "delivered" | "failed" | "pending" | "retrying" | "sending" | "sent";

export type OperatorAlertKind = "held_lead" | "new_lead" | "reminder";

export type OperatorAlertStatus = "cancelled" | "dead" | "pending" | "retrying" | "sending" | "sent";

export type OwnershipType = "landlord" | "owner" | "tenant";

export type PropertyType = "bungalow" | "commercial" | "flat" | "house";

export type RecipientModel = "first_party" | "shared_multiple" | "shared_one";

export type RoutingOutcome = "assigned" | "error" | "no_candidates" | "skipped";

export type RoutingRuleKind = "filter" | "limiter" | "ranker";

export type SaleType = "exclusive" | "shared";

export type SuppressionKind = "email" | "phone";

export type SuppressionReason = "erasure" | "opt_out" | "tps" | "withdrawn_consent";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UrgencyLevel = "emergency" | "just_planning" | "within_1_month" | "within_2_weeks";

export interface AssignmentContactAttempts {
  assignment_id: string;
  created_by: string | null;
  id: Generated<string>;
  job_value_pence: number | null;
  note: string | null;
  occurred_at: Generated<Timestamp>;
  outcome: ContactOutcome;
}

export interface AssignmentStatusTransitions {
  from_status: AssignmentStatus;
  to_status: AssignmentStatus;
}

export interface AuditLogs {
  action: string;
  actor_id: string | null;
  actor_type: ActorType;
  after: Json | null;
  before: Json | null;
  entity_id: string;
  entity_type: string;
  id: Generated<Int8>;
  ip: string | null;
  occurred_at: Generated<Timestamp>;
  reason: string | null;
  request_id: string | null;
  user_agent: string | null;
}

export interface ClientChangeRequests {
  client_id: string;
  created_at: Generated<Timestamp>;
  done_at: Timestamp | null;
  done_by: string | null;
  id: Generated<string>;
  kind: ChangeRequestKind;
  message: string;
  requested_by: string;
  status: Generated<ChangeRequestStatus>;
}

export interface ClientLoginTokens {
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  token_hash: Buffer;
  user_id: string;
}

export interface ClientPauses {
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  ends_at: Timestamp;
  id: Generated<string>;
  reason: string;
  starts_at: Timestamp;
}

export interface Clients {
  accepts_exclusive: Generated<boolean>;
  accepts_shared: Generated<boolean>;
  billing_mode: Generated<BillingMode>;
  company_number: string | null;
  contact_email: string;
  contact_name: string | null;
  contact_phone_e164: string | null;
  created_at: Generated<Timestamp>;
  daily_lead_cap: number | null;
  deleted_at: Timestamp | null;
  delivery_enabled_at: Timestamp | null;
  delivery_mode: Generated<DeliveryMode>;
  id: Generated<string>;
  legal_name: string | null;
  max_open_leads: number | null;
  monthly_lead_cap: number | null;
  name: string;
  notes: string | null;
  notify_email: Generated<boolean>;
  notify_sms: Generated<boolean>;
  notify_webhook: Generated<boolean>;
  priority: Generated<number>;
  status: Generated<ClientStatus>;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
  vertical_id: number;
  webhook_failing_since: Timestamp | null;
  webhook_secret_enc: string | null;
  webhook_secret_hint: string | null;
  webhook_url: string | null;
  weight: Generated<number>;
}

export interface ClientServiceAreas {
  active: Generated<boolean>;
  center_postcode: string | null;
  client_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: CoverageKind;
  mode: Generated<CoverageMode>;
  outward: string | null;
  postcode_prefix: string | null;
  radius_m: number | null;
  sector: string | null;
  service_area_id: number | null;
}

export interface ClientServices {
  client_id: string;
  service_type_id: number;
}

export interface ClientSessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  last_seen_at: Generated<Timestamp>;
  revoked_at: Timestamp | null;
  token_hash: Buffer;
  user_id: string;
}

export interface ClientUsers {
  client_id: string;
  created_at: Generated<Timestamp>;
  disabled_at: Timestamp | null;
  email: string;
  id: Generated<string>;
  invited_by: string | null;
  last_login_at: Timestamp | null;
  name: string;
  role: Generated<ClientUserRole>;
  status: Generated<ClientUserStatus>;
  updated_at: Generated<Timestamp>;
}

export interface ClientWallets {
  balance_pence: Generated<Int8>;
  client_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ClientWorkingHours {
  client_id: string;
  closes: string;
  opens: string;
  weekday: number;
}

export interface ConsentRecords {
  captured_at: Generated<Timestamp>;
  consent_text_id: number;
  event: Generated<ConsentEventType>;
  id: Generated<string>;
  ip: string | null;
  lead_id: string;
  method: Generated<string>;
  page_path: string | null;
  user_agent: string | null;
}

export interface ConsentTexts {
  body: string;
  body_sha256: string;
  channels: string[];
  code: string;
  created_at: Generated<Timestamp>;
  effective_from: Generated<Timestamp>;
  id: Generated<number>;
  max_recipients: number;
  recipient_model: RecipientModel;
  retired_at: Timestamp | null;
  version: string;
}

export interface CreditLedger {
  amount_pence: Int8;
  assignment_id: string | null;
  balance_after_pence: Int8;
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  entry_type: LedgerEntryType;
  id: Generated<Int8>;
  idempotency_key: string;
  reason: string | null;
}

export interface Disputes {
  assignment_id: string;
  client_id: string;
  created_at: Generated<Timestamp>;
  decided_at: Timestamp | null;
  decided_by: string | null;
  decision_reason: string | null;
  description: string | null;
  id: Generated<string>;
  raised_by: string;
  reason: DisputeReason;
  resolution: DisputeResolution | null;
  status: Generated<DisputeStatus>;
  updated_at: Generated<Timestamp>;
}

export interface LeadAssignments {
  accepted_at: Timestamp | null;
  assigned_by: AssignedBy;
  assigned_by_user_id: string | null;
  client_id: string;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  id: Generated<string>;
  lead_id: string;
  notified_at: Timestamp | null;
  price_pence: number;
  pricing_rule_id: string | null;
  rejected_at: Timestamp | null;
  rejection_reason: string | null;
  reserved_at: Generated<Timestamp>;
  respond_by: Timestamp | null;
  routing_run_id: string | null;
  sale_type: SaleType;
  status: Generated<AssignmentStatus>;
  updated_at: Generated<Timestamp>;
}

export interface LeadAssignmentStatusHistory {
  actor_id: string | null;
  actor_type: ActorType;
  assignment_id: string;
  created_at: Generated<Timestamp>;
  from_status: AssignmentStatus | null;
  id: Generated<Int8>;
  reason: string | null;
  request_id: string | null;
  to_status: AssignmentStatus;
}

export interface LeadAttributions {
  created_at: Generated<Timestamp>;
  fbclid: string | null;
  gclid: string | null;
  landing_path: string | null;
  lead_id: string;
  msclkid: string | null;
  referrer_host: string | null;
  utm_campaign: string | null;
  utm_content: string | null;
  utm_medium: string | null;
  utm_source: string | null;
  utm_term: string | null;
}

export interface LeadCharges {
  amount_pence: number;
  assignment_id: string;
  client_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  ledger_entry_id: Int8 | null;
  reversal_ledger_entry_id: Int8 | null;
  reversed_at: Timestamp | null;
  source: ChargeSource;
  status: Generated<ChargeStatus>;
}

export interface LeadContacts {
  created_at: Generated<Timestamp>;
  email: string | null;
  email_normalised: string | null;
  erased_at: Timestamp | null;
  full_name: string | null;
  ip: string | null;
  lead_id: string;
  notes: string | null;
  phone_e164: string | null;
  user_agent: string | null;
}

export interface LeadEvents {
  actor_id: string | null;
  actor_type: Generated<ActorType>;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  lead_id: string;
  payload: Generated<Json>;
  request_id: string | null;
  type: string;
}

export interface LeadFraudSignals {
  code: string;
  created_at: Generated<Timestamp>;
  detail: Generated<Json>;
  id: Generated<Int8>;
  lead_id: string;
  weight: number;
}

export interface Leads {
  assignments_count: Generated<number>;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  details: Generated<Json>;
  duplicate_of_lead_id: string | null;
  erased_at: Timestamp | null;
  fraud_decision: FraudDecision;
  fraud_score: number;
  id: Generated<string>;
  idempotency_key: string;
  is_test: Generated<boolean>;
  max_assignments: Generated<number>;
  ownership: OwnershipType;
  payload_fingerprint: string;
  postcode: string | null;
  postcode_outward: string;
  property_type: PropertyType;
  reference: string;
  routing_attempted_at: Timestamp | null;
  sale_model: SaleType | null;
  service_type_id: number;
  source_id: number;
  status: LeadStatus;
  status_changed_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
  urgency: UrgencyLevel;
  vertical_id: number;
}

export interface LeadSources {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  kind: LeadSourceKind;
  name: string;
  slug: string;
}

export interface LeadStatusHistory {
  actor_id: string | null;
  actor_type: ActorType;
  created_at: Generated<Timestamp>;
  from_status: LeadStatus | null;
  id: Generated<Int8>;
  lead_id: string;
  reason: string | null;
  request_id: string | null;
  to_status: LeadStatus;
}

export interface LeadStatusTransitions {
  from_status: LeadStatus;
  to_status: LeadStatus;
}

export interface NotificationAttempts {
  attempt_no: number;
  error_code: string | null;
  finished_at: Generated<Timestamp>;
  http_status: number | null;
  id: Generated<Int8>;
  latency_ms: number | null;
  notification_id: string;
  outcome: string;
  started_at: Timestamp;
}

export interface Notifications {
  assignment_id: string;
  attempt_count: Generated<number>;
  channel: NotificationChannel;
  created_at: Generated<Timestamp>;
  delivered_at: Timestamp | null;
  id: Generated<string>;
  last_error_code: string | null;
  locked_until: Timestamp | null;
  max_attempts: Generated<number>;
  next_attempt_at: Generated<Timestamp>;
  provider_message_id: string | null;
  sent_at: Timestamp | null;
  status: Generated<NotificationStatus>;
  updated_at: Generated<Timestamp>;
}

export interface OperatorAlertAttempts {
  alert_id: string;
  attempt_no: number;
  error_code: string | null;
  finished_at: Generated<Timestamp>;
  http_status: number | null;
  id: Generated<Int8>;
  latency_ms: number | null;
  outcome: string;
  started_at: Timestamp;
}

export interface OperatorAlerts {
  attempt_count: Generated<number>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: OperatorAlertKind;
  last_error_code: string | null;
  lead_id: string;
  locked_until: Timestamp | null;
  max_attempts: Generated<number>;
  next_attempt_at: Generated<Timestamp>;
  provider_message_id: string | null;
  sent_at: Timestamp | null;
  status: Generated<OperatorAlertStatus>;
  updated_at: Generated<Timestamp>;
}

export interface Operators {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
}

export interface Postcodes {
  admin_district_code: string | null;
  area: Generated<string>;
  country_code: string | null;
  introduced_on: Timestamp | null;
  lat: number | null;
  lng: number | null;
  loaded_at: Generated<Timestamp>;
  outward: Generated<string>;
  postcode: string;
  region_code: string | null;
  sector: Generated<string>;
  source: Generated<string>;
  terminated_on: Timestamp | null;
}

export interface PricingRules {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  currency: Generated<string>;
  id: Generated<string>;
  price_pence: number;
  priority: Generated<number>;
  sale_type: SaleType;
  service_area_id: number | null;
  service_type_id: number | null;
  urgency: UrgencyLevel | null;
  valid_during: Generated<string>;
  vertical_id: number;
}

export interface ProviderEvents {
  error_code: string | null;
  event_id: string;
  id: Generated<Int8>;
  processed_at: Timestamp | null;
  provider: string;
  provider_message_id: string | null;
  received_at: Generated<Timestamp>;
  status: string;
}

export interface RoutingRules {
  active: Generated<boolean>;
  config: Generated<Json>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: RoutingRuleKind;
  position: number;
  type: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
  vertical_id: number;
}

export interface RoutingRuns {
  algorithm_version: string;
  candidates: Generated<Json>;
  chosen_client_id: string | null;
  created_at: Generated<Timestamp>;
  duration_ms: number | null;
  error: string | null;
  id: Generated<string>;
  lead_id: string;
  outcome: RoutingOutcome;
  price_pence: number | null;
  rules: Json;
}

export interface RoutingSettings {
  enabled: Generated<boolean>;
  enabled_at: Timestamp | null;
  max_lead_age_hours: Generated<number>;
  poked_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  vertical_id: number;
}

export interface ServiceAreaDistricts {
  outward: string;
  service_area_id: number;
}

export interface ServiceAreas {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  slug: string;
  updated_at: Generated<Timestamp>;
}

export interface ServiceTypes {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  label: string;
  slug: string;
  sort_order: Generated<number>;
  updated_at: Generated<Timestamp>;
  vertical_id: number;
}

export interface Suppressions {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: SuppressionKind;
  last_requested_at: Generated<Timestamp>;
  reason: SuppressionReason;
  value_hmac: string;
}

export interface Verticals {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  duplicate_window_days: Generated<number>;
  id: Generated<number>;
  name: string;
  slug: string;
  updated_at: Generated<Timestamp>;
}

export interface VerticalServiceAreas {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  service_area_id: number;
  vertical_id: number;
}

export interface VMoneyProblems {
  client_id: string | null;
  problem: string | null;
}

export interface WorkerHeartbeats {
  last_beat_at: Generated<Timestamp>;
  last_reconciled_at: Timestamp | null;
  started_at: Generated<Timestamp>;
  worker_id: string;
}

export interface DB {
  assignment_contact_attempts: AssignmentContactAttempts;
  assignment_status_transitions: AssignmentStatusTransitions;
  audit_logs: AuditLogs;
  client_change_requests: ClientChangeRequests;
  client_login_tokens: ClientLoginTokens;
  client_pauses: ClientPauses;
  client_service_areas: ClientServiceAreas;
  client_services: ClientServices;
  client_sessions: ClientSessions;
  client_users: ClientUsers;
  client_wallets: ClientWallets;
  client_working_hours: ClientWorkingHours;
  clients: Clients;
  consent_records: ConsentRecords;
  consent_texts: ConsentTexts;
  credit_ledger: CreditLedger;
  disputes: Disputes;
  lead_assignment_status_history: LeadAssignmentStatusHistory;
  lead_assignments: LeadAssignments;
  lead_attributions: LeadAttributions;
  lead_charges: LeadCharges;
  lead_contacts: LeadContacts;
  lead_events: LeadEvents;
  lead_fraud_signals: LeadFraudSignals;
  lead_sources: LeadSources;
  lead_status_history: LeadStatusHistory;
  lead_status_transitions: LeadStatusTransitions;
  leads: Leads;
  notification_attempts: NotificationAttempts;
  notifications: Notifications;
  operator_alert_attempts: OperatorAlertAttempts;
  operator_alerts: OperatorAlerts;
  operators: Operators;
  postcodes: Postcodes;
  pricing_rules: PricingRules;
  provider_events: ProviderEvents;
  routing_rules: RoutingRules;
  routing_runs: RoutingRuns;
  routing_settings: RoutingSettings;
  service_area_districts: ServiceAreaDistricts;
  service_areas: ServiceAreas;
  service_types: ServiceTypes;
  suppressions: Suppressions;
  v_money_problems: VMoneyProblems;
  vertical_service_areas: VerticalServiceAreas;
  verticals: Verticals;
  worker_heartbeats: WorkerHeartbeats;
}
